'use strict';
(()=>{
 const $=id=>document.getElementById(id),video=$('film'),D=window.PANTANAL_CONTENT,Media=window.PantanalMedia;
 const seen=new Set();let phase='intro',started=false,unlocked=false,tab='fauna',page=0,selected=null,detail=0,menuOpen=true,zoom=1,muted=false,narrating=false,token=0,lastTime=0,question=0,answered=false,wrong=false,feedback='',attempts=0,score=0,chapter=-1,toastTimer,playbackMessage='';
 const getItem=id=>D.items.find(x=>x.id===id),faunaSeen=()=>D.items.filter(x=>x.category==='fauna'&&seen.has(x.id)).length;
 const inVR=()=>document.body.classList.contains('xr-active');
 const clock=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
 function status(message='',temporary=false){clearTimeout(toastTimer);$('status').textContent=message;if(temporary)toastTimer=setTimeout(()=>status(),4000);}
 function syncAudio(){video.muted=muted||narrating;}
 function stopVoice(){token++;window.speechSynthesis?.cancel();narrating=false;syncAudio();}
 function playbackState(){$('resume').hidden=!started||!video.paused;$('playback-alert').hidden=!started||!video.paused;$('playback-message').textContent=playbackMessage||'Selecione o botão para continuar com som.';emit();}
 async function keepPlaying(){if(!started||!Media.ready)return false;video.loop=true;try{if(video.paused)await video.play();playbackMessage='';playbackState();return true;}catch(error){playbackMessage=error.name==='NotAllowedError'?'O navegador pediu um clique para reproduzir com som. Selecione “Continuar vídeo”.':'Não foi possível iniciar a reprodução. Selecione “Continuar vídeo” para tentar novamente.';playbackState();return false;}}
 async function fullscreen(){if(inVR())return;try{if(!$('app').requestFullscreen)return;if(document.fullscreenElement)await document.exitFullscreen();else await $('app').requestFullscreen();}catch{status('A experiência continua na janela do navegador.',true);}}
 async function start(immersive=false){if(!Media.ready){await Media.prepare();return false;}if(started)return keepPlaying();started=true;phase=unlocked?'explore':'watching';stopVoice();status();const playing=keepPlaying();if(!immersive&&!document.fullscreenElement)fullscreen();render();return playing;}
 function unlockExploration(){if(!Media.ready)return false;unlocked=true;phase='explore';menuOpen=true;render();status('Selecione um animal no caderno ou um ponto nas cenas.',true);return true;}
 function exploreNow(){if(!unlockExploration())return;if(started)return keepPlaying();return window.PantanalVR?.supported?window.PantanalVR.enter():start();}
 function replay(){if(!Media.ready)return;stopVoice();seen.clear();unlocked=false;selected=null;feedback='';question=0;score=0;lastTime=0;zoom=1;video.currentTime=0;started=false;start(inVR());}
 function mediaControls(){
  const busy=Media.state==='loading',vrReady=window.PantanalVR?.supported,percent=Math.min(100,Math.floor(Media.loaded/Media.total*100));
  $('start').disabled=busy;$('start').textContent=busy?(Media.streaming?'Preparando vídeo…':`Carregando · ${percent}%`):Media.ready?(vrReady?'▶ Começar em VR':'▶ Começar em tela cheia'):!Media.sourceURL?'Selecionar vídeo no aparelho':Media.state==='error'?'↻ Tentar carregar novamente':'↓ Carregar vídeo';
  $('start-explore').hidden=!Media.ready;$('start-explore').textContent=vrReady?'Explorar animais em VR':'Explorar animais agora';$('apply-url').disabled=busy;$('remote-url').disabled=busy;$('use-package').disabled=busy;$('watch-flat').hidden=!Media.ready||!vrReady;$('choose-video').disabled=busy;$('load-status').dataset.state=Media.state;
  $('load-message').textContent=Media.message||'Selecione o MP4 de 7min55s no aparelho ou use o link do vídeo na Webnode.';
  $('load-progress').hidden=!busy;if(busy&&Media.streaming)$('load-progress').removeAttribute('value');else $('load-progress').value=percent;$('load-progress').setAttribute('aria-valuetext',`${percent}%`);
  $('load-help').textContent=Media.detail;$('load-help').hidden=!Media.detail;
 }
 function back(){if(!unlocked)return;stopVoice();phase='explore';selected=null;feedback='';menuOpen=true;render();keepPlaying();}
 function chooseTab(value){if(!unlocked)return;status();stopVoice();tab=value;page=0;selected=null;phase='explore';menuOpen=true;feedback='';render();}
 function changePage(delta){const n=Math.ceil(listItems().length/4);page=Math.max(0,Math.min(n-1,page+delta));render();}
 function jump(time){if(!unlocked)return;video.currentTime=Math.max(0,Math.min(video.duration-.2,time));keepPlaying();}
 function showItem(id,seek=true){if(!unlocked)return;status();const d=getItem(id);if(!d)return;stopVoice();selected=id;detail=0;phase='explore';menuOpen=true;tab=d.category;feedback='';seen.add(id);render();if(seek)jump(d.time);}
 function nextDetail(){stopVoice();const d=getItem(selected);if(!d)return;detail=(detail+1)%d.pages.length;render();}
 function speak(){if(narrating){stopVoice();render();return;}const d=getItem(selected);if(!d)return;if(!window.speechSynthesis||!window.SpeechSynthesisUtterance){status('A voz não está disponível neste navegador. Leia a explicação na ficha.',true);return;}
  stopVoice();const version=token,u=new SpeechSynthesisUtterance(`${d.label}. ${d.pages[detail][0]}. ${d.pages[detail][1]}`);u.lang='pt-BR';u.rate=.94;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang==='pt-BR')||voices.find(v=>v.lang.startsWith('pt'))||null;
  const finish=failed=>{if(version!==token)return;narrating=false;syncAudio();if(failed)status('A narração não está disponível. A ficha continua na tela.',true);render();};u.onend=()=>finish(false);u.onerror=()=>finish(true);narrating=true;syncAudio();speechSynthesis.speak(u);render();
 }
 function mute(){muted=!muted;stopVoice();syncAudio();render();}
 function setZoom(z){zoom=Math.min(inVR()?1.35:1.65,Math.max(inVR() ? .35 : .65,z));layout();render();}
 function resetSize(){setZoom(1);}
 function startQuiz(){if(faunaSeen()<7)return;stopVoice();selected=null;phase='quiz';menuOpen=true;question=0;score=0;attempts=0;answered=false;wrong=false;feedback='';render();keepPlaying();}
 function answer(i){if(phase!=='quiz'||answered)return;attempts++;const q=D.quiz[question];wrong=i!==q.correct;answered=!wrong;if(answered){if(attempts===1)score++;feedback=q.why;}else feedback='Tente novamente. Use o que você observou nas fichas e no vídeo.';render();}
 function nextQuestion(){if(!answered)return;question++;feedback='';wrong=false;answered=false;attempts=0;if(question>=D.quiz.length)phase='complete';render();}
 function listItems(){return tab==='cenas'?D.chapters:D.items.filter(x=>x.category===tab);}
 function playbackView(){return{title:'Continuar vídeo',label:'REPRODUÇÃO COM SOM',body:playbackMessage||'Selecione “Continuar vídeo” para retomar. Suas descobertas foram preservadas.',actions:[{label:'Continuar vídeo',run:keepPlaying}]};}
 function view(){
  if(phase==='intro')return{title:'Pantanal imersivo',label:'BEM-VINDO À EXPEDIÇÃO',body:'Escolha explorar os animais agora ou acompanhar primeiro a viagem completa.',actions:[{label:'Começar',run:()=>start(inVR())}]};
  if(phase==='watching')return{title:'Acompanhe a viagem',label:'PRIMEIRA EXIBIÇÃO',body:'Acompanhe a viagem ou selecione Animais para começar a explorar. O vídeo segue em movimento.',actions:[]};
  if(phase==='quiz'){const q=D.quiz[question];return{title:q.title,label:`DESAFIO ${question+1} DE ${D.quiz.length}`,body:q.body,feedback,wrong,actions:answered?[{label:question===D.quiz.length-1?'Concluir expedição':'Próximo desafio →',run:nextQuestion}]:q.options.map((label,i)=>({label,run:()=>answer(i)}))};}
  if(phase==='complete')return{title:'Expedição concluída!',label:'CADERNO DE CAMPO',body:`Você conheceu os 7 animais e concluiu os 5 desafios. Acertos na primeira tentativa: ${score}/5. Continue explorando as águas e os ambientes.`,actions:[{label:'Continuar explorando',run:back},{label:'Refazer desafios',run:startQuiz}]};
  const d=getItem(selected);if(d)return{title:d.label,label:`${d.pages[detail][0]} · ${detail+1}/${d.pages.length}`,scientific:d.scientific,body:d.pages[detail][1],source:d.source,actions:[{label:'Próxima página →',run:nextDetail},{label:'Ver cena novamente',run:()=>jump(d.time)},{label:narrating?'Parar explicação':'Ouvir explicação',run:speak}]};
  const values=listItems(),max=Math.ceil(values.length/4);return{title:tab==='fauna'?'Animais do Pantanal':tab==='ambientes'?'Ambientes e relações':'Trechos da viagem',label:`${page+1} / ${max}`,body:'Escolha uma descoberta. O vídeo continua em movimento.',menu:values.slice(page*4,page*4+4).map((d,i)=>({label:d.label,id:d.id||'cena-'+(page*4+i),time:d.time,image:d.image,visited:seen.has(d.id),run:()=>tab==='cenas'?jump(d.time):showItem(d.id)})),page,max,actions:[]};
 }
 function emit(){document.dispatchEvent(new CustomEvent('pantanal-render'));}
 function render(){
  const v=view();document.body.dataset.phase=phase;$('intro').hidden=phase!=='intro';$('explorer').hidden=!unlocked||!menuOpen;$('tools').hidden=!unlocked;$('watch-note').hidden=phase!=='watching';$('chapter-tag').hidden=!unlocked;
  $('mode-badge').textContent=unlocked?'EXPLORAÇÃO LIBERADA · VÍDEO EM LOOP':phase==='watching'?'PRIMEIRA EXIBIÇÃO':'EXPEDIÇÃO IMERSIVA';
  $('tabs').hidden=phase==='quiz'||phase==='complete';document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
  $('panel-eyebrow').textContent=selected?'FICHA DE DESCOBERTA':phase==='quiz'?'MISSÃO PANTANAL':'CADERNO DE CAMPO';
  $('close-panel').setAttribute('aria-label',selected||phase!=='explore'?'Voltar ao caderno':'Recolher caderno');
  const hasCard=!!selected||phase==='quiz'||phase==='complete';$('card').hidden=!hasCard;$('catalog').hidden=hasCard;$('pagination').hidden=hasCard;
  if(hasCard){$('scientific').textContent=v.scientific||'';$('scientific').hidden=!v.scientific;$('card-title').textContent=v.title;$('card-page').textContent=v.label;$('card-body').textContent=v.body;$('card-feedback').hidden=!v.feedback;$('card-feedback').textContent=v.feedback||'';$('card-feedback').classList.toggle('wrong',!!v.wrong);$('card-source').hidden=!v.source;if(v.source)$('card-source').href=v.source;
   $('card-actions').replaceChildren(...v.actions.map((a,i)=>{const b=document.createElement('button');b.textContent=a.label;b.onclick=a.run;if(i===0)b.classList.add('primary');return b;}));
  }else if(unlocked){$('catalog').replaceChildren(...v.menu.map((a,i)=>{const b=document.createElement('button');b.className='catalog-item';b.id='item-'+a.id;b.onclick=a.run;const image=document.createElement(a.image?'img':'b');if(a.image){image.src=a.image;image.alt='';}else{image.className='number';image.textContent=String(page*4+i+1).padStart(2,'0');}const s=document.createElement('span'),title=document.createElement('strong'),small=document.createElement('small');title.textContent=a.label;small.textContent=clock(a.time)+' · Ver cena';s.append(title,small);const check=document.createElement('b');check.className='visited';check.textContent=a.visited?'✓':'↗';b.append(image,s,check);return b;}));$('page-number').textContent=`${v.page+1} / ${v.max}`;$('prev-page').disabled=page===0;$('next-page').disabled=page>=v.max-1;}
  $('discovered').textContent=`${seen.size} / ${D.items.length}`;$('discovered-bar').style.width=seen.size/D.items.length*100+'%';$('quiz').textContent=`◇ Desafios · ${faunaSeen()}/7`;$('quiz').disabled=faunaSeen()<7;$('audio').textContent=muted?'Som desligado':'Som ligado';playbackState();mediaControls();layout();updateTime();emit();
 }
 function activeSpots(){if(!unlocked||phase!=='explore')return[];const t=video.currentTime;return D.tracks.flatMap(track=>{const k=track.keys;if(t<k[0][0]||t>=k.at(-1)[0])return[];let i=0;while(i<k.length-2&&t>k[i+1][0])i++;const a=k[i],b=k[i+1],mix=(t-a[0])/(b[0]-a[0]);return[{id:track.id,x:a[1]+(b[1]-a[1])*mix,y:a[2]+(b[2]-a[2])*mix}];});}
 const spotElements=new Map();D.items.filter(d=>d.category==='fauna').forEach((d,i)=>{const b=document.createElement('button');b.className='spot';b.hidden=true;b.setAttribute('aria-label','Conhecer '+d.label);b.textContent=String(i+1);const label=document.createElement('span');label.textContent=d.label;b.append(label);b.onclick=()=>showItem(d.id,false);$('hotspots').append(b);spotElements.set(d.id,b);});
 function updateTime(){const duration=Number.isFinite(video.duration)?video.duration:475.12,t=video.currentTime;$('time').textContent=`${unlocked?'↻ ':''}${clock(t)} / ${clock(duration)}`;$('time-bar').style.width=Math.min(100,t/duration*100)+'%';$('watch-message').textContent=`Faltam ${clock(Math.max(0,duration-t))} para liberar as interações.`;
  const c=D.chapters.findLastIndex(x=>t>=x.time);if(c!==chapter){chapter=c;$('chapter-title').textContent=D.chapters[Math.max(0,c)].label;emit();}
  const spots=activeSpots();for(const [id,b]of spotElements){const point=spots.find(x=>x.id===id);b.hidden=!point;if(point){b.style.left=point.x*100+'%';b.style.top=point.y*100+'%';}}
 }
 function onTime(){const t=video.currentTime,d=video.duration;if(started&&!unlocked&&Number.isFinite(d)&&lastTime>d*.75&&t<d*.25){unlocked=true;phase='explore';menuOpen=true;render();status('Exploração liberada! Selecione os animais ou os temas.',true);}lastTime=t;updateTime();}
 function layout(){const r=$('stage').getBoundingClientRect();let top=0,height=r.height;if(r.width<r.height&&unlocked&&menuOpen){top=133;height=Math.max(110,$('explorer').getBoundingClientRect().top-top-10);}const w=Math.min(r.width,height*16/9)*zoom,h=w*9/16;for(const id of ['film','hotspots']){$(id).style.width=w+'px';$(id).style.height=h+'px';$(id).style.left=(r.width-w)/2+'px';$(id).style.top=top+(height-h)/2+'px';}}
 function stepChapter(direction){if(!unlocked)return;const current=Math.max(0,D.chapters.findLastIndex(x=>video.currentTime>=x.time));jump(D.chapters[(current+direction+D.chapters.length)%D.chapters.length].time);}
 $('start').onclick=()=>!Media.ready?(Media.sourceURL?Media.prepare():$('local-video').click()):window.PantanalVR?.supported?window.PantanalVR.enter():start();$('watch-flat').onclick=()=>start();$('start-explore').onclick=exploreNow;$('explore-during').onclick=exploreNow;$('remote-url').value=Media.sourceURL;$('remote-form').onsubmit=event=>{event.preventDefault();Media.useURL($('remote-url').value);};$('use-package').onclick=()=>{Media.usePackage();$('remote-url').value='';$('local-video').click();};$('choose-video').onclick=()=>$('local-video').click();$('local-video').onchange=event=>{Media.useFile(event.target.files[0]);event.target.value='';};document.addEventListener('pantanal-media',mediaControls);
 $('vr-button').onclick=()=>window.PantanalVR?.enter();$('audio').onclick=mute;$('resume').onclick=keepPlaying;$('retry-play').onclick=keepPlaying;$('restart').onclick=replay;$('fullscreen').onclick=fullscreen;$('open-notebook').onclick=()=>{if(!unlocked)return;menuOpen=!menuOpen;render();};$('close-panel').onclick=()=>{if(selected||phase!=='explore')back();else{menuOpen=false;render();}};
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>chooseTab(b.dataset.tab));$('prev-page').onclick=()=>changePage(-1);$('next-page').onclick=()=>changePage(1);$('smaller').onclick=()=>setZoom(zoom-.1);$('larger').onclick=()=>setZoom(zoom+.1);$('reset-size').onclick=resetSize;$('quiz').onclick=startQuiz;
 video.addEventListener('timeupdate',onTime);video.addEventListener('loadedmetadata',updateTime);video.addEventListener('playing',()=>{playbackMessage='';playbackState();});video.addEventListener('pause',playbackState);video.addEventListener('ended',keepPlaying);video.addEventListener('error',()=>{if(started){playbackMessage='O navegador não conseguiu reproduzir o vídeo. Recarregue a página e tente novamente.';playbackState();}});
 if(video.requestVideoFrameCallback){const frame=()=>{onTime();video.requestVideoFrameCallback(frame);};video.requestVideoFrameCallback(frame);}
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)keepPlaying();else stopVoice();});document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'Sair da tela cheia':'Tela cheia ⛶';layout();});new ResizeObserver(layout).observe($('stage'));
 window.Pantanal={data:D,video,view,playbackView,render,mediaControls,status,start,unlockExploration,exploreNow,keepPlaying,replay,back,chooseTab,changePage,showItem,stepChapter,startQuiz,mute,speak,resetSize,stopVoice,activeSpots,zoomBy:delta=>setZoom(zoom+delta),primary:()=>video.paused?keepPlaying():selected?speak():mute(),get needsResume(){return started&&video.paused},get phase(){return phase},get unlocked(){return unlocked},get selected(){return selected},get zoom(){return zoom},get muted(){return muted},get visitedCount(){return seen.size},get faunaCount(){return faunaSeen()},get chapter(){return D.chapters[Math.max(chapter,0)].label}};
 render();
})();
